// <auto-generated />
namespace Movies.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class manytomanyrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomanyrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201808271136540_many to many relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
