// <auto-generated />
namespace Movies.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removesuserprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removesuserprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "201808271247169_removes user profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
